package mynote.gui;
import handlers.Global;
import mynote.*;
import mynote.Event.LabelMouseEvent;
/**
 *
 * @author ebennamr
 */
public class Home extends javax.swing.JPanel implements updatableView{

private  void Setup()
{
    LabelMouseEvent even = new LabelMouseEvent(Views.LOGIN);
    lblLogout.addMouseMotionListener(even);
    lblLogout.addMouseListener(even);
    
    
      even = new LabelMouseEvent(Views.NEW_NOTE);
    lblNewNote.addMouseMotionListener(even);
    lblNewNote.addMouseListener(even);

     even = new LabelMouseEvent(Views.PROFILE);
    lblProfile.addMouseMotionListener(even);
    lblProfile.addMouseListener(even);


}



    public Home() {
        initComponents();
        
        
        Setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContianer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        leftSide = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblProgramIcon = new javax.swing.JLabel();
        lblProgramName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblProfile = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblNewNote = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NotePanelContainer = new javax.swing.JPanel();
        notePanel1 = new mynote.gui.notePanel();
        notePanel2 = new mynote.gui.notePanel();
        notePanel3 = new mynote.gui.notePanel();
        notePanel4 = new mynote.gui.notePanel();
        notePanel5 = new mynote.gui.notePanel();
        notePanel6 = new mynote.gui.notePanel();
        notePanel7 = new mynote.gui.notePanel();
        notePanel8 = new mynote.gui.notePanel();
        notePanel9 = new mynote.gui.notePanel();

        setBackground(new java.awt.Color(33, 28, 106));
        setForeground(CONST.SECONDARY_COLLOR);
        setLocation(new java.awt.Point(500, 500));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.BorderLayout());

        mainContianer.setOpaque(false);
        mainContianer.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(443, 66));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        leftSide.setMaximumSize(new java.awt.Dimension(20, 32767));
        leftSide.setMinimumSize(new java.awt.Dimension(10, 0));
        leftSide.setOpaque(false);
        leftSide.setPreferredSize(new java.awt.Dimension(30, 500));
        leftSide.setRequestFocusEnabled(false);

        javax.swing.GroupLayout leftSideLayout = new javax.swing.GroupLayout(leftSide);
        leftSide.setLayout(leftSideLayout);
        leftSideLayout.setHorizontalGroup(
            leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        leftSideLayout.setVerticalGroup(
            leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel1.add(leftSide);

        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/avatar.png"))); // NOI18N
        jPanel1.add(lblAvatar);

        lblUserName.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(239, 243, 150));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("alphaben");
        lblUserName.setMaximumSize(new java.awt.Dimension(120, 64));
        lblUserName.setMinimumSize(new java.awt.Dimension(120, 64));
        lblUserName.setPreferredSize(new java.awt.Dimension(64, 120));
        lblUserName.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(lblUserName);

        lblProgramIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/logo.png"))); // NOI18N
        jPanel1.add(lblProgramIcon);

        lblProgramName.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        lblProgramName.setForeground(new java.awt.Color(239, 243, 150));
        lblProgramName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProgramName.setText("My Note");
        lblProgramName.setMaximumSize(new java.awt.Dimension(120, 64));
        lblProgramName.setMinimumSize(new java.awt.Dimension(120, 64));
        lblProgramName.setPreferredSize(new java.awt.Dimension(64, 120));
        lblProgramName.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(lblProgramName);

        mainContianer.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setOpaque(false);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(239, 243, 150));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Notes");
        jLabel4.setMaximumSize(new java.awt.Dimension(444, 32));
        jLabel4.setMinimumSize(new java.awt.Dimension(0, 32));
        jLabel4.setPreferredSize(new java.awt.Dimension(42, 32));

        MenuPanel.setMaximumSize(new java.awt.Dimension(32767, 40));
        MenuPanel.setMinimumSize(new java.awt.Dimension(0, 40));
        MenuPanel.setOpaque(false);
        MenuPanel.setPreferredSize(new java.awt.Dimension(0, 40));
        MenuPanel.setLayout(new javax.swing.BoxLayout(MenuPanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setForeground(new java.awt.Color(239, 243, 150));
        jLabel3.setToolTipText("");
        jLabel3.setMaximumSize(new java.awt.Dimension(20, 17));
        jLabel3.setMinimumSize(new java.awt.Dimension(20, 17));
        MenuPanel.add(jLabel3);

        lblProfile.setForeground(new java.awt.Color(239, 243, 150));
        lblProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/user.png"))); // NOI18N
        lblProfile.setText("Profile");
        MenuPanel.add(lblProfile);

        jLabel10.setForeground(new java.awt.Color(239, 243, 150));
        jLabel10.setToolTipText("");
        jLabel10.setMaximumSize(new java.awt.Dimension(20, 17));
        jLabel10.setMinimumSize(new java.awt.Dimension(20, 17));
        MenuPanel.add(jLabel10);

        lblNewNote.setForeground(new java.awt.Color(239, 243, 150));
        lblNewNote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/new.png"))); // NOI18N
        lblNewNote.setText("New");
        MenuPanel.add(lblNewNote);

        jLabel11.setForeground(new java.awt.Color(239, 243, 150));
        jLabel11.setToolTipText("");
        jLabel11.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel11.setMinimumSize(new java.awt.Dimension(130, 17));
        MenuPanel.add(jLabel11);

        lblLogout.setForeground(new java.awt.Color(239, 243, 150));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/logout.png"))); // NOI18N
        lblLogout.setText("logout");
        lblLogout.setMaximumSize(new java.awt.Dimension(120, 32));
        lblLogout.setMinimumSize(new java.awt.Dimension(120, 32));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
        });
        MenuPanel.add(lblLogout);

        NotePanelContainer.setBackground(new java.awt.Color(239, 243, 150));
        NotePanelContainer.setMaximumSize(new java.awt.Dimension(400, 360));
        NotePanelContainer.setMinimumSize(new java.awt.Dimension(400, 360));
        NotePanelContainer.setPreferredSize(new java.awt.Dimension(400, 360));
        NotePanelContainer.setLayout(new javax.swing.BoxLayout(NotePanelContainer, javax.swing.BoxLayout.Y_AXIS));
        NotePanelContainer.add(notePanel1);
        NotePanelContainer.add(notePanel2);
        NotePanelContainer.add(notePanel3);
        NotePanelContainer.add(notePanel4);
        NotePanelContainer.add(notePanel5);
        NotePanelContainer.add(notePanel6);
        NotePanelContainer.add(notePanel7);
        NotePanelContainer.add(notePanel8);
        NotePanelContainer.add(notePanel9);

        jScrollPane1.setViewportView(NotePanelContainer);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        mainContianer.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(mainContianer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
     
      Session.DeleteCurrentSession();
      handlers.Handler.getHandler().DeleteSession(Global.Session.getSessionId());
      
      Global.CurrentNote = null;
      Global.Session = null;
      Global.CurrentNote = null;
    }//GEN-LAST:event_lblLogoutMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel NotePanelContainer;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblNewNote;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblProgramIcon;
    private javax.swing.JLabel lblProgramName;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel leftSide;
    private javax.swing.JPanel mainContianer;
    private mynote.gui.notePanel notePanel1;
    private mynote.gui.notePanel notePanel2;
    private mynote.gui.notePanel notePanel3;
    private mynote.gui.notePanel notePanel4;
    private mynote.gui.notePanel notePanel5;
    private mynote.gui.notePanel notePanel6;
    private mynote.gui.notePanel notePanel7;
    private mynote.gui.notePanel notePanel8;
    private mynote.gui.notePanel notePanel9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateView() 
    {
       NotePanelContainer.removeAll();
       Note.notes.clear();
       if(Global.Session == null)
       {
            if (Session.isSessionFileExsists())
                handlers.Handler.getHandler().LoadSession(Session.getSessionID());
            else 
                Frame.getInstance().SetView(Views.LOGIN);    
       }
       
        handlers.Handler.getHandler().FillNote();
         for( Note note : Note.notes)
         {
             NotePanelContainer.add(new notePanel(note));
         }
         
         NotePanelContainer.validate();
         jScrollPane1.getVerticalScrollBar().setValue(0);
         jScrollPane1.getVerticalScrollBar().setValue(100);
         jScrollPane1.getVerticalScrollBar().setValue(0);
    }
}
