package mynote.gui;
import handlers.Global;
import mynote.*;
import mynote.Event.LabelMouseEvent;

public class Profile extends javax.swing.JPanel implements updatableView{


    
    
    
public  void Setup()
{
    LabelMouseEvent even = new LabelMouseEvent(Views.HOME);
    lblBack.addMouseMotionListener(even);
    lblBack.addMouseListener(even);
   
}

    public Profile() {
        initComponents();
         Setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContianer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        leftSide = new javax.swing.JPanel();
        lblBack = new javax.swing.JLabel();
        lblProgramIcon = new javax.swing.JLabel();
        lblProgramName = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblProfileIcon = new javax.swing.JLabel();
        InfoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 28, 106));
        setForeground(CONST.SECONDARY_COLLOR);
        setLocation(new java.awt.Point(500, 500));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.BorderLayout());

        mainContianer.setOpaque(false);
        mainContianer.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(443, 66));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        leftSide.setMaximumSize(new java.awt.Dimension(20, 32767));
        leftSide.setMinimumSize(new java.awt.Dimension(10, 0));
        leftSide.setOpaque(false);
        leftSide.setPreferredSize(new java.awt.Dimension(30, 500));
        leftSide.setRequestFocusEnabled(false);

        javax.swing.GroupLayout leftSideLayout = new javax.swing.GroupLayout(leftSide);
        leftSide.setLayout(leftSideLayout);
        leftSideLayout.setHorizontalGroup(
            leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        leftSideLayout.setVerticalGroup(
            leftSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        jPanel1.add(leftSide);

        lblBack.setFont(new java.awt.Font("Helvetica Neue", 0, 26)); // NOI18N
        lblBack.setForeground(new java.awt.Color(239, 243, 150));
        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/back.png"))); // NOI18N
        lblBack.setText("Back");
        lblBack.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblBack.setMaximumSize(new java.awt.Dimension(120, 40));
        lblBack.setMinimumSize(new java.awt.Dimension(120, 40));
        lblBack.setPreferredSize(new java.awt.Dimension(120, 40));
        jPanel1.add(lblBack);

        lblProgramIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/logo.png"))); // NOI18N
        jPanel1.add(lblProgramIcon);

        lblProgramName.setFont(new java.awt.Font("Helvetica Neue", 1, 26)); // NOI18N
        lblProgramName.setForeground(new java.awt.Color(239, 243, 150));
        lblProgramName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProgramName.setText("My Note");
        lblProgramName.setMaximumSize(new java.awt.Dimension(120, 64));
        lblProgramName.setMinimumSize(new java.awt.Dimension(120, 64));
        lblProgramName.setPreferredSize(new java.awt.Dimension(64, 120));
        lblProgramName.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(lblProgramName);

        mainContianer.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setOpaque(false);

        lblProfileIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/avatar.png"))); // NOI18N

        InfoPanel.setOpaque(false);
        InfoPanel.setLayout(new java.awt.GridLayout(0, 2, 5, 0));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(239, 243, 150));
        jLabel3.setText("FirstName");
        InfoPanel.add(jLabel3);

        lblFirstName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(239, 243, 150));
        lblFirstName.setText("El Mehdi");
        InfoPanel.add(lblFirstName);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(239, 243, 150));
        jLabel5.setText("last Name");
        InfoPanel.add(jLabel5);

        lblLastName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(239, 243, 150));
        lblLastName.setText("Bennamrouche");
        InfoPanel.add(lblLastName);

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(239, 243, 150));
        jLabel11.setText("UserName");
        InfoPanel.add(jLabel11);

        lblUserName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(239, 243, 150));
        lblUserName.setText("alphaben");
        InfoPanel.add(lblUserName);

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(239, 243, 150));
        jLabel13.setText("Email");
        InfoPanel.add(jLabel13);

        lblEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(239, 243, 150));
        lblEmail.setText("example. rout.data@gamil.com");
        InfoPanel.add(lblEmail);

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(239, 243, 150));
        jLabel15.setText("Gender");
        InfoPanel.add(jLabel15);

        lblGender.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(239, 243, 150));
        lblGender.setText("Male");
        InfoPanel.add(lblGender);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProfileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblProfileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        mainContianer.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(mainContianer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblProfileIcon;
    private javax.swing.JLabel lblProgramIcon;
    private javax.swing.JLabel lblProgramName;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel leftSide;
    private javax.swing.JPanel mainContianer;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateView() {
   User us = Global.currentUser;
    if ( us == null)
        return;

    lblEmail.setText(us.getEmail());
    lblFirstName.setText(us.getFirstName());
    lblGender.setText(us.getGender());
    lblLastName.setText(us.getLastName());
    lblUserName.setText(us.getUserName());
    }
}
